export const mockUsers = [
  {
    id: 1,
    firstName: 'Emily',
    lastName: 'Johnson',
    age: 28,
    username: 'ejohnson',
    email: 'HqgsJt5@example.com',
  },
  {
    id: 2,
    firstName: 'Michael',
    lastName: 'Williams',
    age: 35,
    username: 'mwilliams',
    email: 'jJq125Jt@example.com',
  },
  {
    id: 3,
    firstName: 'Sophia',
    lastName: 'Brown',
    age: 42,
    username: 'sbrown',
    email: 'jJq224Jt@example.com',
  },

  {
    id: 4,
    firstName: 'James',
    lastName: 'Davis',
    age: 45,
    username: 'jdavis',
    email: 'jJq11Jt@example.com',
  },
  {
    id: 5,
    firstName: 'Emma',
    lastName: 'Miller',
    age: 30,
    username: 'emiller',
    email: 'jJqgg12Jt@example.com',
  },
  {
    id: 6,
    firstName: 'Olivia',
    lastName: 'Wilson',
    age: 22,
    username: 'owilson',
    email: 'jJq1g2g2Jt@example.com',
  },
  {
    id: 7,
    firstName: 'Alexander',
    lastName: 'Jones',
    age: 38,
    username: 'ajones',
    email: 'jJq2gggx2Jt@example.com',
  },
  {
    id: 8,
    firstName: 'Ava',
    lastName: 'Taylor',
    age: 27,
    username: 'ataylor',
    email: 'jJq3ggdd22gx2Jt@example.com',
  },
  {
    id: 9,
    firstName: 'Ethan',
    lastName: 'Martinez',
    age: 33,
    username: 'emartinez',
    email: 'jJgx2Jt@example.com',
  },
  {
    id: 10,
    firstName: 'Isabella',
    lastName: 'Anderson',
    age: 31,
    username: 'ianderson',
    email: 'jJq4g111Jt@example.com',
  },
]
